export const metadata = {
    title: 'My Next App | About',
    description: 'Generated by create next app',
  }

const AboutPage = () => {
    return (
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
            About
        </div>
    );
};

export default AboutPage;