'use client';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="mx-auto text-center mt-4 items-center">
          <a href="/" className='me-2'>Home</a>
          <a href="/about" className='me-2'>About</a>
          <a href="/profile" className='me-2'>Profile</a>
          <a href="/blogs" className='me-2'>Blogs</a>
        </nav>
        {children}
        <footer className='text-center'>
          Footer
        </footer>
      </body>
    </html>
  )
}

export default RootLayout;
