export const metadata = {
    title: 'Profile | My Next App',
    description: 'Generated by create next app',
  }

const ProfilePage = () => {
    return (
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
            profile
        </div>
    );
};

export default ProfilePage;