export const metadata = {
    title: 'Dashboard | My Next App',
    description: 'Generated by create next app',
}

const DashboardLayout = ({ children }) => {
    return (
        <div>
            <div>
                sidebar
            </div>
            {children}
        </div>
    );
};

export default DashboardLayout;